### ISSUE TITLE
release branch!

### ISSUE THREAD

**Issue by AtiyahElsheikh** [OpenModelica/BioChem#16]
I was thinking about the release branch. 

Initially, Is it really needed? First there are no high activities in this library. Second, one can still access the releases through the tags. Or is there something I am missing? 

Another issue, the top folder is the directory Biochem. Under release branch it is Biochem1.0.1 . Should this folder be renamed to Biochem/ and replaced by version 1.0.2? Or shall another folder with the name 1.0.2 be placed under release? 

Any thoughts?

**Comment by sjoelund** [comment]
I think it's enough to tag releases and stay in master. Having the release branch is extra work.

**Comment by AtiyahElsheikh** [comment]
release branch deleted!

**Comment by casella** [comment]
> I think it's enough to tag releases and stay in master. Having the release branch is extra work.

Yes, that's what I normally do with domain-specific Modelica libraries. Huge libraries like the MSL may need some more release management, but I guess that's not the case here.
