### ISSUE TITLE
Embedded annotations in components 

### ISSUE THREAD

**Issue by AtiyahElsheikh** [OpenModelica/BioChem#24]
There are a high number of embedded graphical annotations in many components, see e.g. the [Interfaces.Reactions](https://github.com/OpenModelica/BioChem/tree/master/BioChem/Interfaces/Reactions) package. 

The goal is to move all graphical annotations to relevant components within the [Icons package](https://github.com/OpenModelica/BioChem/tree/develop/BioChem/Icons) (say in a 1-to-1 mapping fashion)  

It is not really wise to do it in a manual manner. 

I see that I can do it with Java or Python since graphical annotations have a lot of common structures within the BioChem library (It seems they were added in automatic fashion). 

However, my question: 

> Would it be straightforward to do it with the current set of available functions for *.mos script? or tricky and error-prone?

**Comment by sjoelund** [comment]
In OMEdit, you could simply copy-paste the icon layer from a class to a new Icons class, right? Then remove the graphics from the original and extend from the icon?

**Comment by sjoelund** [comment]
I'm not sure how to script it in OpenModelica mos-scripts, but that might also be possible.

**Comment by AtiyahElsheikh** [comment]
> In OMEdit, you could simply copy-paste the icon layer from a class to a new Icons class, right? (And remove the components automatically added) Then remove the graphics from the original and extend from the icon?

Yes I can do that. Due to a high number of available components (See, [Reactions.*](https://github.com/OpenModelica/BioChem/tree/develop/BioChem/Reactions) or [Interfaces.Reactions.*](https://github.com/OpenModelica/BioChem/tree/develop/BioChem/Interfaces/Reactions)), I am simply looking for a simpler way to do it.

**Comment by sjoelund** [comment]
I'm a bit busy with other things, but I think you could from mos-scripts (or OMPython):

```mo
// First get a list of classes to extract icons from and where to put them
copyClass(...);
// Delete extends possible in the API?
deleteComponent(x, BioChem.Icons.yyy); // loop in OMPython
// save this to file
// update the package.order?
```

And then have a list of what should extend from these icons; remove icons for these and extend from the corresponding icon. Call the diff API to make it not break. 

But I don't have time to implement that :D

**Comment by AtiyahElsheikh** [comment]
Thanks 

I will give it a trial some time this week. If I feel it is tedious, for the short-term I would rather focus for a while on GenKinetics, and do only the chages I need in BioChem. But on the long-term I guess this seems to be a doable task.
