### ISSUE TITLE
Wrong extends in BioChem.Icons.Substances.SignalSubstance

### ISSUE THREAD

**Issue by perost** [OpenModelica/BioChem#31]
`BioChem.Icons.Substances.SignalSubstance` currently contains this extends:
https://github.com/OpenModelica/BioChem/blob/70166071b0bf6ae24686add66aafc6156de5e4cf/BioChem/Icons/Substances/SignalSubstance.mo#L4
I suspect this is a typo and it should actually be `BioChem.Icons.Interfaces.Substances.InputSubstance`. Otherwise it causes issues with e.g. `BioChem.Substances.SignalSubstance` that because of this indirectly extends `BioChem.Interfaces.Substances.InputSubstance` twice and becomes unbalanced due to too many equations.

**Comment by AtiyahElsheikh** [comment]
@perost feel free to add your name in UsersGuide.ReleaseNotes
